# Generated by Django 5.2.11 on 2026-02-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_productline_site_department_code_department_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='field_level_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Module.field: read/write/hidden'),
        ),
        migrations.AddField(
            model_name='role',
            name='ui_visibility_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Module: visible/hidden'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_deactivation_date',
            field=models.DateTimeField(blank=True, help_text='Date when account was deactivated', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deactivation_reason',
            field=models.CharField(blank=True, help_text='Reason for account deactivation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='external_access_expiry',
            field=models.DateTimeField(blank=True, help_text='When external access expires', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_external_auditor',
            field=models.BooleanField(default=False, help_text='User is an external auditor'),
        ),
    ]
