# Generated by Django 5.2.11 on 2026-02-25 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('supplier_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('service_provider', 'Service Provider'), ('raw_material', 'Raw Material Supplier'), ('component', 'Component Supplier'), ('calibration', 'Calibration Service'), ('sterilization', 'Sterilization Service'), ('other', 'Other')], max_length=50)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('qualification_status', models.CharField(choices=[('not_qualified', 'Not Qualified'), ('pending_evaluation', 'Pending Evaluation'), ('pending_audit', 'Pending Audit'), ('qualified', 'Qualified'), ('conditionally_qualified', 'Conditionally Qualified'), ('suspended', 'Suspended'), ('disqualified', 'Disqualified')], default='not_qualified', max_length=30)),
                ('qualified_date', models.DateField(blank=True, null=True)),
                ('next_evaluation_date', models.DateField(blank=True, null=True)),
                ('qualification_notes', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('risk_justification', models.TextField(blank=True)),
                ('iso_certified', models.BooleanField(default=False)),
                ('iso_certificate_number', models.CharField(blank=True, max_length=100)),
                ('iso_expiry_date', models.DateField(blank=True, null=True)),
                ('regulatory_registrations', models.JSONField(blank=True, null=True)),
                ('gmp_compliant', models.BooleanField(default=False)),
                ('products_services', models.JSONField(blank=True, null=True)),
                ('approved_materials', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='users.department')),
                ('quality_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_suppliers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issue_description', models.TextField()),
                ('scar_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending_response', 'Pending Response'), ('response_received', 'Response Received'), ('verified', 'Verified'), ('closed', 'Closed')], default='open', max_length=30)),
                ('response_due_date', models.DateField()),
                ('response_received_date', models.DateField(blank=True, null=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('verification_result', models.TextField(blank=True)),
                ('capa', models.CharField(blank=True, help_text='Reference to CAPA (Corrective & Preventive Action) module', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='suppliers.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_supplier_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Corrective Action',
                'verbose_name_plural': 'Supplier Corrective Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('quality_agreement', 'Quality Agreement'), ('certificate', 'Certificate'), ('audit_report', 'Audit Report'), ('corrective_action', 'Corrective Action'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='supplier_documents/%Y/%m/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='suppliers.supplier')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_supplier_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Document',
                'verbose_name_plural': 'Supplier Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('evaluation_date', models.DateField()),
                ('evaluation_type', models.CharField(choices=[('initial', 'Initial Evaluation'), ('periodic', 'Periodic Evaluation'), ('for_cause', 'For Cause Evaluation'), ('re_evaluation', 'Re-evaluation')], max_length=30)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('delivery_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('service_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('compliance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comments', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('approve', 'Approve'), ('conditionally_approve', 'Conditionally Approve'), ('reject', 'Reject'), ('re_evaluate', 'Re-evaluate')], max_length=30)),
                ('next_evaluation_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_evaluations', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='suppliers.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Evaluation',
                'verbose_name_plural': 'Supplier Evaluations',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_id'], name='suppliers_s_supplie_590c06_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['qualification_status', 'risk_level'], name='suppliers_s_qualifi_e2084d_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['department', 'qualification_status'], name='suppliers_s_departm_d6b1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_type'], name='suppliers_s_supplie_c9bf31_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercorrectiveaction',
            index=models.Index(fields=['supplier', 'status'], name='suppliers_s_supplie_909959_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercorrectiveaction',
            index=models.Index(fields=['scar_number'], name='suppliers_s_scar_nu_6993b9_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercorrectiveaction',
            index=models.Index(fields=['response_due_date'], name='suppliers_s_respons_6db013_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdocument',
            index=models.Index(fields=['supplier', 'document_type'], name='suppliers_s_supplie_e45b69_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierevaluation',
            index=models.Index(fields=['supplier', 'evaluation_date'], name='suppliers_s_supplie_2f9a25_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierevaluation',
            index=models.Index(fields=['evaluation_type'], name='suppliers_s_evaluat_9f0372_idx'),
        ),
    ]
