# Generated by Django 5.2.11 on 2026-02-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='approved_scope',
            field=models.CharField(blank=True, help_text='e.g., Approved for packaging only', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='auto_quarantine_on_cert_expiry',
            field=models.BooleanField(default=True, help_text='Automatically quarantine supplier on certificate expiry'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='portal_access_enabled',
            field=models.BooleanField(default=False, help_text='Supplier can access supplier portal'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='portal_email',
            field=models.EmailField(blank=True, help_text='Portal login email for supplier', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_category',
            field=models.CharField(blank=True, choices=[('drug_component', 'Drug Component'), ('device_component', 'Device Component'), ('packaging', 'Packaging'), ('service', 'Service'), ('raw_material', 'Raw Material'), ('other', 'Other')], default='other', help_text='Supplier category', max_length=30),
        ),
    ]
