# Generated by Django 5.2.11 on 2026-02-25 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.IntegerField()),
                ('is_repeatable', models.BooleanField(default=False)),
                ('conditions', models.JSONField(blank=True, help_text='Conditional show/hide logic', null=True)),
            ],
            options={
                'verbose_name': 'Form Section',
                'verbose_name_plural': 'Form Sections',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('datetime', 'Date & Time'), ('time', 'Time'), ('email', 'Email'), ('url', 'URL'), ('phone', 'Phone'), ('checkbox', 'Checkbox'), ('radio', 'Radio Button'), ('dropdown', 'Dropdown'), ('multi_select', 'Multi-Select'), ('file_upload', 'File Upload'), ('image_upload', 'Image Upload'), ('signature', 'Signature'), ('rating', 'Rating'), ('scale', 'Scale'), ('matrix', 'Matrix'), ('formula', 'Formula'), ('conditional', 'Conditional'), ('yes_no', 'Yes/No'), ('pass_fail', 'Pass/Fail')], max_length=50)),
                ('help_text', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('sequence', models.IntegerField()),
                ('options', models.JSONField(blank=True, help_text='For radio/dropdown/multi_select: list of {value, label}', null=True)),
                ('validation_rules', models.JSONField(blank=True, help_text='Validation rules: min, max, regex, etc.', null=True)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('scoring_weight', models.IntegerField(default=0, help_text='Weight for scored forms')),
                ('conditions', models.JSONField(blank=True, help_text='Conditional visibility logic', null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form_builder.formsection')),
            ],
            options={
                'verbose_name': 'Form Question',
                'verbose_name_plural': 'Form Questions',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('audit_checklist', 'Audit Checklist'), ('investigation_form', 'Investigation Form'), ('deviation_checklist', 'Deviation Checklist'), ('protocol', 'Protocol'), ('inspection_form', 'Inspection Form'), ('review_form', 'Review Form'), ('custom', 'Custom')], max_length=50)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates', to='users.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Template',
                'verbose_name_plural': 'Form Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='formsection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='form_builder.formtemplate'),
        ),
        migrations.CreateModel(
            name='FormInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('context_type', models.CharField(blank=True, help_text='What this form is attached to (e.g., audit, deviation)', max_length=100)),
                ('context_id', models.CharField(blank=True, max_length=100)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_possible_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_forms', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='form_builder.formtemplate')),
            ],
            options={
                'verbose_name': 'Form Instance',
                'verbose_name_plural': 'Form Instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True)),
                ('response_number', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('response_boolean', models.BooleanField(blank=True, null=True)),
                ('response_json', models.JSONField(blank=True, help_text='For complex responses: multi_select, matrix', null=True)),
                ('response_file', models.FileField(blank=True, null=True, upload_to='form_responses/%Y/%m/')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='form_builder.forminstance')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='form_builder.formquestion')),
            ],
            options={
                'verbose_name': 'Form Response',
                'verbose_name_plural': 'Form Responses',
                'indexes': [models.Index(fields=['instance', 'question'], name='form_builde_instanc_3cc2f1_idx')],
                'unique_together': {('instance', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='formquestion',
            index=models.Index(fields=['section', 'sequence'], name='form_builde_section_508c81_idx'),
        ),
        migrations.AddIndex(
            model_name='formquestion',
            index=models.Index(fields=['question_type'], name='form_builde_questio_50dd45_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['template_type', 'is_published'], name='form_builde_templat_83a743_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['department', 'is_active'], name='form_builde_departm_52f52b_idx'),
        ),
        migrations.AddIndex(
            model_name='formsection',
            index=models.Index(fields=['template', 'sequence'], name='form_builde_templat_221ce0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formsection',
            unique_together={('template', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='forminstance',
            index=models.Index(fields=['template', 'status'], name='form_builde_templat_cc82df_idx'),
        ),
        migrations.AddIndex(
            model_name='forminstance',
            index=models.Index(fields=['context_type', 'context_id'], name='form_builde_context_193956_idx'),
        ),
        migrations.AddIndex(
            model_name='forminstance',
            index=models.Index(fields=['completed_by', 'created_at'], name='form_builde_complet_15e36a_idx'),
        ),
    ]
