# Generated by Django 5.2.11 on 2026-02-26 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('checkbox', 'Checkbox'), ('radio', 'Radio Button'), ('dropdown', 'Dropdown'), ('multi_select', 'Multi-Select'), ('file_upload', 'File Upload'), ('signature', 'Signature'), ('rating', 'Rating'), ('matrix', 'Matrix'), ('formula', 'Formula'), ('conditional', 'Conditional'), ('section_break', 'Section Break'), ('instruction', 'Instruction'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL'), ('calculated', 'Calculated')], max_length=50),
        ),
        migrations.CreateModel(
            name='ConditionalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than')], max_length=50)),
                ('condition_value', models.CharField(max_length=500)),
                ('action', models.CharField(choices=[('show', 'Show'), ('hide', 'Hide'), ('require', 'Make Required')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_rules', to='form_builder.formquestion')),
                ('target_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions_targeting_this', to='form_builder.formquestion')),
            ],
            options={
                'verbose_name': 'Conditional Rule',
                'verbose_name_plural': 'Conditional Rules',
                'ordering': ['form_question__sequence'],
            },
        ),
    ]
