# Generated by Django 5.2.11 on 2026-02-26 12:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electronicsignature',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='electronicsignature',
            name='signed_at',
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='invalidated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invalidated_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='invalidation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='is_valid',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='signature_meaning',
            field=models.CharField(choices=[('approval', 'Approval'), ('rejection', 'Rejection'), ('review', 'Review'), ('acknowledgment', 'Acknowledgment'), ('verification', 'Verification'), ('authoring', 'Authoring')], default='approval', max_length=30),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='reason',
            field=models.CharField(blank=True, choices=[('approval', 'Document Approval'), ('review', 'Document Review'), ('capa_closure', 'CAPA Closure'), ('complaint_closure', 'Complaint Closure'), ('audit_closure', 'Audit Closure'), ('training_completion', 'Training Completion'), ('change_approval', 'Change Order Approval')], max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='electronicsignature',
            index=models.Index(fields=['content_type', 'object_id'], name='core_electr_content_d7091a_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicsignature',
            index=models.Index(fields=['signer', 'timestamp'], name='core_electr_signer__518338_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicsignature',
            index=models.Index(fields=['is_valid'], name='core_electr_is_vali_074163_idx'),
        ),
    ]
