# Generated by Django 5.2.11 on 2026-02-25 01:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deviation_id', models.CharField(editable=False, help_text='Auto-generated ID in format DEV-YYYY-NNNN', max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deviation_type', models.CharField(choices=[('planned', 'Planned'), ('unplanned', 'Unplanned')], max_length=20)),
                ('category', models.CharField(choices=[('product', 'Product'), ('process', 'Process'), ('system', 'System'), ('documentation', 'Documentation'), ('equipment', 'Equipment'), ('material', 'Material'), ('environmental', 'Environmental'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('observation', 'Observation')], max_length=20)),
                ('source', models.CharField(choices=[('production', 'Production'), ('laboratory', 'Laboratory'), ('warehouse', 'Warehouse'), ('incoming_inspection', 'Incoming Inspection'), ('customer_complaint', 'Customer Complaint'), ('audit_finding', 'Audit Finding'), ('self_inspection', 'Self Inspection'), ('other', 'Other')], max_length=25)),
                ('source_reference', models.TextField(blank=True, null=True)),
                ('process_affected', models.TextField()),
                ('product_affected', models.TextField()),
                ('batch_lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_affected', models.IntegerField(blank=True, null=True)),
                ('impact_assessment', models.TextField()),
                ('patient_safety_impact', models.BooleanField(default=False)),
                ('current_stage', models.CharField(choices=[('opened', 'Opened'), ('qa_review', 'QA Review'), ('investigation', 'Investigation'), ('capa_plan', 'CAPA Plan'), ('pending_capa_approval', 'Pending CAPA Approval'), ('pending_capa_completion', 'Pending CAPA Completion'), ('pending_final_approval', 'Pending Final Approval'), ('completed', 'Completed')], default='opened', max_length=30)),
                ('stage_entered_at', models.DateTimeField(auto_now_add=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('investigation_summary', models.TextField(blank=True, null=True)),
                ('investigation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('corrective_action', models.TextField(blank=True, null=True)),
                ('preventive_action', models.TextField(blank=True, null=True)),
                ('disposition', models.CharField(blank=True, choices=[('use_as_is', 'Use As Is'), ('rework', 'Rework'), ('reject', 'Reject'), ('return_to_supplier', 'Return to Supplier'), ('scrap', 'Scrap'), ('other', 'Other')], max_length=25, null=True)),
                ('disposition_justification', models.TextField(blank=True, null=True)),
                ('reported_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_closure_date', models.DateTimeField(blank=True, null=True)),
                ('actual_closure_date', models.DateTimeField(blank=True, null=True)),
                ('requires_capa', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('regulatory_reportable', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations_assigned', to=settings.AUTH_USER_MODEL)),
                ('capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations', to='capa.capa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deviations', to='users.department')),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations_investigated', to=settings.AUTH_USER_MODEL)),
                ('qa_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations_reviewed', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deviations_reported', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='DeviationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='deviations/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='deviations.deviation')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deviation_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('stage', models.CharField(blank=True, choices=[('opened', 'Opened'), ('qa_review', 'QA Review'), ('investigation', 'Investigation'), ('capa_plan', 'CAPA Plan'), ('pending_capa_approval', 'Pending CAPA Approval'), ('pending_capa_completion', 'Pending CAPA Completion'), ('pending_final_approval', 'Pending Final Approval'), ('completed', 'Completed')], help_text='Stage at which this comment was made', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deviation_comments', to=settings.AUTH_USER_MODEL)),
                ('deviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='deviations.deviation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='deviations.deviationcomment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deviation',
            index=models.Index(fields=['deviation_id'], name='deviations__deviati_ad9f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='deviation',
            index=models.Index(fields=['current_stage'], name='deviations__current_43b99e_idx'),
        ),
        migrations.AddIndex(
            model_name='deviation',
            index=models.Index(fields=['severity'], name='deviations__severit_5b1578_idx'),
        ),
        migrations.AddIndex(
            model_name='deviation',
            index=models.Index(fields=['department'], name='deviations__departm_57babc_idx'),
        ),
    ]
