# Generated by Django 5.2.11 on 2026-02-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviation',
            name='affected_batch_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of affected batch numbers'),
        ),
        migrations.AddField(
            model_name='deviation',
            name='auto_escalated_to_capa',
            field=models.BooleanField(default=False, help_text='Deviation auto-escalated to CAPA'),
        ),
        migrations.AddField(
            model_name='deviation',
            name='escalation_reason',
            field=models.CharField(blank=True, help_text='Reason for escalation to CAPA', max_length=200, null=True),
        ),
    ]
