# Generated by Django 5.2.11 on 2026-02-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviations', '0002_deviation_affected_batch_numbers_and_more'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviation',
            name='linked_equipment',
            field=models.ForeignKey(blank=True, help_text='Equipment involved in deviation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='deviation',
            name='risk_occurrence',
            field=models.IntegerField(blank=True, help_text='1-5 risk occurrence score', null=True),
        ),
        migrations.AddField(
            model_name='deviation',
            name='risk_score',
            field=models.IntegerField(blank=True, help_text='Auto-calculated: severity * occurrence', null=True),
        ),
        migrations.AddField(
            model_name='deviation',
            name='risk_severity',
            field=models.IntegerField(blank=True, help_text='1-5 risk severity score', null=True),
        ),
    ]
