# Generated by Django 5.2.11 on 2026-02-24 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_id', models.CharField(max_length=50, unique=True)),
                ('audit_type', models.CharField(choices=[('internal', 'Internal'), ('supplier', 'Supplier')], max_length=20)),
                ('scope', models.TextField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='planned', max_length=20)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('findings_count', models.IntegerField(default=0)),
                ('major_nc', models.IntegerField(default=0)),
                ('minor_nc', models.IntegerField(default=0)),
                ('observations', models.IntegerField(default=0)),
                ('next_audit_planned', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lead_auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_plans_led', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Plan',
                'verbose_name_plural': 'Audit Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('major_nc', 'Major Non-Conformance'), ('minor_nc', 'Minor Non-Conformance'), ('observation', 'Observation')], max_length=20)),
                ('description', models.TextField()),
                ('evidence', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('capa_assigned', 'CAPA Assigned'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('target_closure_date', models.DateField(blank=True, null=True)),
                ('actual_closure_date', models.DateField(blank=True, null=True)),
                ('assigned_capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to='capa.capa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit_mgmt.auditplan')),
            ],
            options={
                'verbose_name': 'Audit Finding',
                'verbose_name_plural': 'Audit Findings',
                'ordering': ['-created_at'],
            },
        ),
    ]
