# Generated by Django 5.2.11 on 2026-02-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_mgmt', '0002_initial'),
        ('capa', '0003_initial'),
        ('form_builder', '0002_alter_formquestion_question_type_conditionalrule'),
        ('suppliers', '0002_supplier_approved_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfinding',
            name='auto_generated_capa',
            field=models.ForeignKey(blank=True, help_text='CAPA auto-generated from this finding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_source_findings', to='capa.capa'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='auto_generated_scar',
            field=models.ForeignKey(blank=True, help_text='Supplier Corrective Action auto-generated from this finding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_source_findings', to='suppliers.suppliercorrectiveaction'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='audit_year',
            field=models.IntegerField(blank=True, help_text='Year of audit for annual planning', null=True),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='auditor_independence_verified',
            field=models.BooleanField(default=False, help_text='Auditor independence has been verified'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='auto_capa_on_major',
            field=models.BooleanField(default=True, help_text='Auto-generate CAPA for major findings'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='auto_scar_on_supplier',
            field=models.BooleanField(default=True, help_text='Auto-generate SCAR for supplier findings'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='checklist_template',
            field=models.ForeignKey(blank=True, help_text='Audit checklist template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_checklists', to='form_builder.formtemplate'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='closure_requires_capa_closed',
            field=models.BooleanField(default=True, help_text='Audit cannot close until all CAPAs are closed'),
        ),
    ]
