# Generated by Django 5.2.11 on 2026-02-26 21:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deviations', '0002_deviation_affected_batch_numbers_and_more'),
        ('suppliers', '0002_supplier_approved_scope_and_more'),
        ('users', '0004_role_field_level_permissions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('equipment_type', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('laboratory', 'Laboratory'), ('testing', 'Testing'), ('packaging', 'Packaging'), ('utility', 'Utility'), ('it_system', 'IT System')], max_length=20)),
                ('category', models.CharField(choices=[('direct_product_contact', 'Direct Product Contact'), ('indirect_product_contact', 'Indirect Product Contact'), ('facility', 'Facility'), ('calibrated_instrument', 'Calibrated Instrument')], max_length=25)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model_number', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('quarantined', 'Quarantined'), ('out_of_service', 'Out of Service'), ('decommissioned', 'Decommissioned'), ('pending_qualification', 'Pending Qualification')], default='pending_qualification', max_length=25)),
                ('criticality', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], default='minor', max_length=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('requires_calibration', models.BooleanField(default=False)),
                ('requires_maintenance', models.BooleanField(default=True)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('interval_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tolerance_specs', models.JSONField(blank=True, default=dict)),
                ('calibration_method', models.CharField(blank=True, max_length=255)),
                ('reference_standards', models.CharField(blank=True, max_length=500)),
                ('last_calibrated', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('auto_quarantine_on_overdue', models.BooleanField(default=True)),
                ('reminder_days_before', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_schedule', to='equipment.equipment')),
            ],
            options={
                'ordering': ['next_due'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('calibration_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('calibration_date', models.DateField()),
                ('as_found_data', models.JSONField(blank=True, default=dict)),
                ('as_left_data', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('adjusted_pass', 'Adjusted Pass'), ('out_of_tolerance', 'Out of Tolerance')], max_length=20)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='equipment/certificates/')),
                ('calibration_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_calibrations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_deviation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deviations.deviation')),
                ('performed_by_internal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_calibrations', to=settings.AUTH_USER_MODEL)),
                ('performed_by_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_calibrations', to='suppliers.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_records', to='equipment.equipment')),
            ],
            options={
                'ordering': ['-calibration_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(choices=[('manual', 'Equipment Manual'), ('sop', 'Standard Operating Procedure'), ('calibration_cert', 'Calibration Certificate'), ('qualification_report', 'Qualification Report'), ('maintenance_log', 'Maintenance Log'), ('spare_parts_list', 'Spare Parts List')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='equipment/documents/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='equipment.equipment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qualification_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('qualification_type', models.CharField(choices=[('iq', 'Installation Qualification (IQ)'), ('oq', 'Operational Qualification (OQ)'), ('pq', 'Performance Qualification (PQ)'), ('requalification', 'Requalification')], max_length=20)),
                ('protocol_number', models.CharField(blank=True, max_length=100)),
                ('protocol_file', models.FileField(blank=True, null=True, upload_to='equipment/protocols/')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='equipment/results/')),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional'), ('not_executed', 'Not Executed')], default='not_executed', max_length=20)),
                ('deviations_noted', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='planned', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_qualifications', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='equipment.equipment')),
                ('qualified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualified_equipment', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('maintenance_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('maintenance_date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('emergency', 'Emergency'), ('predictive', 'Predictive')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('work_performed', models.TextField(blank=True)),
                ('parts_replaced', models.JSONField(blank=True, default=list)),
                ('downtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment')),
                ('linked_deviation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deviations.deviation')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('predictive', 'Predictive')], max_length=20)),
                ('interval_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True)),
                ('last_performed', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='equipment.equipment')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due'],
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_id'], name='equipment_e_equipme_0c3500_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial_number'], name='equipment_e_serial__b7639f_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='equipment_e_status_fb8540_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationschedule',
            index=models.Index(fields=['next_due'], name='equipment_c_next_du_e31001_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationschedule',
            index=models.Index(fields=['equipment'], name='equipment_c_equipme_819f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationrecord',
            index=models.Index(fields=['calibration_id'], name='equipment_c_calibra_b6cb46_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationrecord',
            index=models.Index(fields=['equipment', '-calibration_date'], name='equipment_c_equipme_454b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationrecord',
            index=models.Index(fields=['result'], name='equipment_c_result_113483_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdocument',
            index=models.Index(fields=['equipment', 'document_type'], name='equipment_e_equipme_7fc545_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdocument',
            index=models.Index(fields=['expiry_date'], name='equipment_e_expiry__131f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentqualification',
            index=models.Index(fields=['qualification_id'], name='equipment_e_qualifi_b3694e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentqualification',
            index=models.Index(fields=['equipment', 'qualification_type'], name='equipment_e_equipme_e0ca45_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['maintenance_id'], name='equipment_m_mainten_b2fde5_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['equipment', '-maintenance_date'], name='equipment_m_equipme_95f2eb_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['status'], name='equipment_m_status_9f9d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['equipment', 'maintenance_type'], name='equipment_m_equipme_f38a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['next_due'], name='equipment_m_next_du_46cdf7_idx'),
        ),
    ]
