# Generated by Django 5.2.11 on 2026-02-25 01:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(db_index=True, help_text='Module this workflow applies to: document, capa, deviation, complaint, change_control', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['model_type', 'name'],
                'unique_together': {('name', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, help_text='Specific workflow, or null for all workflows', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowdefinition')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('sequence', models.IntegerField(help_text='Order of this stage in the workflow (1, 2, 3...)')),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color for UI display', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI', max_length=50)),
                ('required_fields', models.JSONField(blank=True, default=list, help_text='Fields that must be non-empty before entering this stage')),
                ('required_attachments', models.BooleanField(default=False, help_text='Whether at least one attachment is required')),
                ('requires_approval', models.BooleanField(default=False)),
                ('required_approvers_count', models.IntegerField(default=0, help_text='Minimum number of approvals needed to pass this stage')),
                ('requires_signature', models.BooleanField(default=False)),
                ('signature_reason', models.CharField(blank=True, help_text="Reason code for electronic signature (e.g., 'approval', 'review')", max_length=100)),
                ('is_initial', models.BooleanField(default=False, help_text='Is this the starting stage for new records?')),
                ('is_terminal', models.BooleanField(default=False, help_text='Is this a final stage (no outgoing transitions)?')),
                ('allows_edit', models.BooleanField(default=True, help_text='Can the record be edited while in this stage?')),
                ('auto_advance', models.BooleanField(default=False, help_text='Auto-advance to next stage when all approvals are met')),
                ('sla_days', models.IntegerField(blank=True, help_text='Expected days to complete this stage (for SLA tracking)', null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.workflowdefinition')),
            ],
            options={
                'ordering': ['workflow', 'sequence'],
                'unique_together': {('workflow', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_stage_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimated_exit_date', models.DateTimeField(blank=True, help_text='SLA deadline for current stage', null=True)),
                ('stage_entry_count', models.IntegerField(default=1, help_text="How many times we've been in the current stage (for reopen tracking)")),
                ('is_active', models.BooleanField(default=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='workflows.workflowdefinition')),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_records', to='workflows.workflowstage')),
            ],
            options={
                'ordering': ['-entered_stage_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowApprovalGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Gate name, e.g., 'QA Review'", max_length=100)),
                ('required_role', models.CharField(help_text='Role required to approve at this gate', max_length=100)),
                ('required_count', models.IntegerField(default=1, help_text='Number of approvals required')),
                ('approval_mode', models.CharField(choices=[('all', 'All must approve'), ('any', 'Any one can approve'), ('majority', 'Majority must approve'), ('count', 'Specific count required')], default='all', max_length=20)),
                ('sequence', models.IntegerField(default=1, help_text='Order of this gate (sequential gates must complete in order)')),
                ('estimated_response_days', models.IntegerField(default=3, help_text='Expected days for approvers to respond')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_gates', to='workflows.workflowstage')),
            ],
            options={
                'ordering': ['stage', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Action label shown in UI (e.g., 'Submit for Review', 'Approve')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('button_color', models.CharField(default='#3B82F6', max_length=20)),
                ('required_permission', models.CharField(blank=True, help_text='Django permission codename required for this transition', max_length=100)),
                ('required_roles', models.JSONField(blank=True, default=list, help_text='List of role names that can execute this transition')),
                ('estimated_duration_days', models.IntegerField(blank=True, help_text='Estimated days for this transition', null=True)),
                ('requires_comment', models.BooleanField(default=False, help_text='Require a comment/reason when executing this transition')),
                ('is_rejection', models.BooleanField(default=False, help_text='Is this a rejection/send-back transition?')),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflows.workflowstage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflows.workflowstage')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflows.workflowdefinition')),
            ],
            options={
                'ordering': ['workflow', 'from_stage__sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transitioned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('time_in_stage_seconds', models.BigIntegerField(blank=True, help_text='How long the record was in from_stage', null=True)),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_transitions', to='core.electronicsignature')),
                ('transitioned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workflow_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflows.workflowrecord')),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflows.workflowstage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflows.workflowstage')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowtransition')),
            ],
            options={
                'ordering': ['-transitioned_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='workflows.workflowapprovalgate')),
                ('signature', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_request', to='core.electronicsignature')),
                ('workflow_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='workflows.workflowrecord')),
            ],
            options={
                'ordering': ['gate__sequence', 'requested_at'],
                'unique_together': {('gate', 'workflow_record', 'approver')},
            },
        ),
        migrations.AddIndex(
            model_name='workflowrecord',
            index=models.Index(fields=['content_type', 'object_id'], name='workflows_w_content_f473e5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrecord',
            index=models.Index(fields=['current_stage', 'is_active'], name='workflows_w_current_b73ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrecord',
            index=models.Index(fields=['is_overdue'], name='workflows_w_is_over_4b0c88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowtransition',
            unique_together={('from_stage', 'to_stage')},
        ),
    ]
