# Generated by Django 5.2.11 on 2026-02-26 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0004_capa_auto_generated_capa_effectiveness_eligible_date_and_more'),
        ('deviations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('material_name', models.CharField(max_length=255)),
                ('material_code', models.CharField(max_length=100)),
                ('lot_number', models.CharField(max_length=100)),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_used', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('verified', 'Verified'), ('consumed', 'Consumed'), ('returned', 'Returned')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Batch Material',
                'verbose_name_plural': 'Batch Materials',
                'ordering': ['batch', 'material_code'],
            },
        ),
        migrations.CreateModel(
            name='BatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_id', models.CharField(editable=False, help_text='Auto-generated Batch ID (e.g., BR-0001)', max_length=50, unique=True)),
                ('batch_number', models.CharField(help_text='Unique batch identifier assigned by production', max_length=100, unique=True)),
                ('lot_number', models.CharField(max_length=100)),
                ('quantity_planned', models.IntegerField()),
                ('quantity_produced', models.IntegerField(blank=True, null=True)),
                ('quantity_rejected', models.IntegerField(default=0)),
                ('yield_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of planned quantity successfully produced', max_digits=5, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('under_review', 'Under Review'), ('released', 'Released'), ('rejected', 'Rejected'), ('quarantined', 'Quarantined')], default='pending', max_length=20)),
                ('production_line', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('has_deviations', models.BooleanField(default=False, help_text='Whether this batch has any deviations')),
                ('review_by_exception', models.BooleanField(default=False, help_text='Whether this batch requires review by exception')),
            ],
            options={
                'verbose_name': 'Batch Record',
                'verbose_name_plural': 'Batch Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('step_number', models.IntegerField()),
                ('instruction_text', models.TextField()),
                ('required_data_fields', models.JSONField(default=list, help_text='List of data fields required for this step')),
                ('actual_values', models.JSONField(default=dict, help_text='Collected data values for this step')),
                ('specifications', models.JSONField(default=dict, help_text='Acceptable parameter ranges')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('deviated', 'Deviated')], default='pending', max_length=20)),
                ('requires_verification', models.BooleanField(default=False)),
                ('operator_signed_at', models.DateTimeField(blank=True, null=True)),
                ('verifier_signed_at', models.DateTimeField(blank=True, null=True)),
                ('deviation_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_within_spec', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Batch Step',
                'verbose_name_plural': 'Batch Steps',
                'ordering': ['batch', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='MasterBatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mbr_id', models.CharField(editable=False, help_text='Auto-generated Master Batch Record ID (e.g., MBR-0001)', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=100)),
                ('version', models.CharField(default='1.0', help_text='Version of the master batch record', max_length=50)),
                ('bill_of_materials', models.JSONField(default=list, help_text='List of materials required for production')),
                ('manufacturing_instructions', models.JSONField(default=list, help_text='Step-by-step manufacturing process')),
                ('quality_specifications', models.JSONField(default=dict, help_text='Quality parameters and acceptance criteria')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('obsolete', 'Obsolete')], default='draft', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Master Batch Record',
                'verbose_name_plural': 'Master Batch Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchDeviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deviation_id', models.CharField(editable=False, help_text='Auto-generated Deviation ID (e.g., BD-0001)', max_length=50, unique=True)),
                ('deviation_type', models.CharField(choices=[('parameter_excursion', 'Parameter Excursion'), ('equipment_failure', 'Equipment Failure'), ('material_issue', 'Material Issue'), ('process_deviation', 'Process Deviation'), ('documentation_error', 'Documentation Error'), ('environmental', 'Environmental')], max_length=50)),
                ('description', models.TextField()),
                ('impact_assessment', models.TextField(blank=True)),
                ('immediate_action', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_deviations', to='capa.capa')),
                ('linked_deviation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_deviations', to='deviations.deviation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_batch_deviations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Deviation',
                'verbose_name_plural': 'Batch Deviations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment_name', models.CharField(max_length=255)),
                ('equipment_id_manual', models.CharField(blank=True, help_text='Manual equipment ID if not linked to equipment database', max_length=100, null=True)),
                ('usage_start', models.DateTimeField(blank=True, null=True)),
                ('usage_end', models.DateTimeField(blank=True, null=True)),
                ('calibration_verified', models.BooleanField(default=False)),
                ('cleaning_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Equipment',
                'verbose_name_plural': 'Batch Equipment',
                'ordering': ['batch', 'equipment_name'],
            },
        ),
    ]
