# Generated by Django 5.2.11 on 2026-02-26 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch_records', '0001_initial'),
        ('documents', '0005_document_requires_dual_approval_and_more'),
        ('equipment', '0001_initial'),
        ('users', '0004_role_field_level_permissions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batchequipment',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_usage', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='batchequipment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchequipment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_batch_equipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchmaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchmaterial',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchmaterial',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchmaterial',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchrecord',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchrecord',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_records', to='users.site'),
        ),
        migrations.AddField(
            model_name='batchrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchmaterial',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='batch_records.batchrecord'),
        ),
        migrations.AddField(
            model_name='batchequipment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_usage', to='batch_records.batchrecord'),
        ),
        migrations.AddField(
            model_name='batchdeviation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='batch_records.batchrecord'),
        ),
        migrations.AddField(
            model_name='batchstep',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='batch_records.batchrecord'),
        ),
        migrations.AddField(
            model_name='batchstep',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchstep',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchstep',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchstep',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchdeviation',
            name='batch_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='batch_records.batchstep'),
        ),
        migrations.AddField(
            model_name='masterbatchrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_master_batch_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterbatchrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterbatchrecord',
            name='linked_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_batch_records', to='documents.document'),
        ),
        migrations.AddField(
            model_name='masterbatchrecord',
            name='product_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_batch_records', to='users.productline'),
        ),
        migrations.AddField(
            model_name='masterbatchrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchrecord',
            name='mbr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_records', to='batch_records.masterbatchrecord'),
        ),
        migrations.AddIndex(
            model_name='batchmaterial',
            index=models.Index(fields=['batch', 'status'], name='batch_recor_batch_i_69e615_idx'),
        ),
        migrations.AddIndex(
            model_name='batchmaterial',
            index=models.Index(fields=['material_code'], name='batch_recor_materia_a7bc1e_idx'),
        ),
        migrations.AddIndex(
            model_name='batchequipment',
            index=models.Index(fields=['batch'], name='batch_recor_batch_i_59eaeb_idx'),
        ),
        migrations.AddIndex(
            model_name='batchequipment',
            index=models.Index(fields=['equipment'], name='batch_recor_equipme_4a33a9_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstep',
            index=models.Index(fields=['batch', 'status'], name='batch_recor_batch_i_3e2a7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batchstep',
            unique_together={('batch', 'step_number')},
        ),
        migrations.AddIndex(
            model_name='batchdeviation',
            index=models.Index(fields=['deviation_id'], name='batch_recor_deviati_a8d867_idx'),
        ),
        migrations.AddIndex(
            model_name='batchdeviation',
            index=models.Index(fields=['batch', 'status'], name='batch_recor_batch_i_f8613b_idx'),
        ),
        migrations.AddIndex(
            model_name='batchdeviation',
            index=models.Index(fields=['deviation_type'], name='batch_recor_deviati_c6c11e_idx'),
        ),
        migrations.AddIndex(
            model_name='masterbatchrecord',
            index=models.Index(fields=['mbr_id'], name='batch_recor_mbr_id_593041_idx'),
        ),
        migrations.AddIndex(
            model_name='masterbatchrecord',
            index=models.Index(fields=['product_code'], name='batch_recor_product_a5d91f_idx'),
        ),
        migrations.AddIndex(
            model_name='masterbatchrecord',
            index=models.Index(fields=['status'], name='batch_recor_status_a8903a_idx'),
        ),
        migrations.AddIndex(
            model_name='batchrecord',
            index=models.Index(fields=['batch_id'], name='batch_recor_batch_i_469cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='batchrecord',
            index=models.Index(fields=['batch_number'], name='batch_recor_batch_n_7f0125_idx'),
        ),
        migrations.AddIndex(
            model_name='batchrecord',
            index=models.Index(fields=['status'], name='batch_recor_status_d244b8_idx'),
        ),
        migrations.AddIndex(
            model_name='batchrecord',
            index=models.Index(fields=['lot_number'], name='batch_recor_lot_num_c41aaf_idx'),
        ),
    ]
