# Generated by Django 5.2.11 on 2026-02-26 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0005_document_requires_dual_approval_and_more'),
        ('users', '0004_role_field_level_permissions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('input_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('specification', models.TextField()),
                ('measurable_criteria', models.TextField()),
                ('input_type', models.CharField(choices=[('functional', 'Functional'), ('performance', 'Performance'), ('safety', 'Safety'), ('regulatory', 'Regulatory'), ('environmental', 'Environmental'), ('interface', 'Interface'), ('packaging', 'Packaging')], max_length=20)),
                ('tolerance', models.CharField(blank=True, max_length=255)),
                ('test_method', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_design_inputs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('device', 'Medical Device'), ('ivd', 'In Vitro Diagnostic'), ('combination', 'Combination Product'), ('drug_device', 'Drug-Device Combination')], max_length=20)),
                ('current_phase', models.CharField(choices=[('planning', 'Planning'), ('design_input', 'Design Input'), ('design_output', 'Design Output'), ('verification', 'Verification'), ('validation', 'Validation'), ('transfer', 'Design Transfer'), ('production', 'Production')], default='planning', max_length=20)),
                ('regulatory_pathway', models.CharField(choices=[('510k', '510(k)'), ('pma', 'PMA'), ('de_novo', 'De Novo'), ('exempt', 'Exempt'), ('ce_mark', 'CE Mark'), ('ivdr', 'IVDR')], max_length=20)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department')),
                ('product_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.productline')),
                ('project_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('output_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('output_type', models.CharField(choices=[('drawing', 'Drawing'), ('specification', 'Specification'), ('software', 'Software'), ('formula', 'Formula'), ('process', 'Process'), ('labeling', 'Labeling')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='design_outputs/')),
                ('revision', models.CharField(blank=True, default='1.0', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_design_outputs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_inputs', models.ManyToManyField(blank=True, related_name='linked_outputs', to='design_controls.designinput')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_outputs', to='design_controls.designproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='designinput',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_inputs', to='design_controls.designproject'),
        ),
        migrations.CreateModel(
            name='DesignReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('review_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('phase', models.CharField(choices=[('planning', 'Planning'), ('design_input', 'Design Input'), ('design_output', 'Design Output'), ('verification', 'Verification'), ('validation', 'Validation'), ('transfer', 'Design Transfer'), ('production', 'Production')], max_length=20)),
                ('review_date', models.DateField()),
                ('agenda', models.TextField(blank=True)),
                ('minutes', models.TextField(blank=True)),
                ('action_items', models.JSONField(default=list)),
                ('outcome', models.CharField(choices=[('approved', 'Approved'), ('conditional', 'Conditional'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], max_length=20)),
                ('conditions', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('attendees', models.ManyToManyField(blank=True, related_name='design_reviews_attended', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_reviews', to='design_controls.designproject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transfer_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('transfer_checklist', models.JSONField(default=list)),
                ('production_readiness_confirmed', models.BooleanField(default=False)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_design_transfers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('manufacturing_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.site')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_transfers', to='design_controls.designproject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('need_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('clinical', 'Clinical'), ('marketing', 'Marketing'), ('regulatory', 'Regulatory'), ('engineering', 'Engineering'), ('manufacturing', 'Manufacturing'), ('customer_feedback', 'Customer Feedback')], max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_user_needs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_needs', to='design_controls.designproject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='designinput',
            name='linked_user_needs',
            field=models.ManyToManyField(blank=True, related_name='linked_inputs', to='design_controls.userneed'),
        ),
        migrations.CreateModel(
            name='VVProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('protocol_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('protocol_type', models.CharField(choices=[('verification', 'Verification'), ('validation', 'Validation')], max_length=20)),
                ('test_method', models.TextField()),
                ('acceptance_criteria', models.TextField()),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('executed', 'Executed'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional'), ('not_executed', 'Not Executed')], default='not_executed', max_length=20)),
                ('result_summary', models.TextField(blank=True)),
                ('deviations_noted', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='vv_protocols/')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='vv_results/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vv_protocols', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_vv_protocols', to=settings.AUTH_USER_MODEL)),
                ('linked_inputs', models.ManyToManyField(blank=True, related_name='vv_protocols', to='design_controls.designinput')),
                ('linked_outputs', models.ManyToManyField(blank=True, related_name='vv_protocols', to='design_controls.designoutput')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vv_protocols', to='design_controls.designproject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceabilityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('link_status', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('missing', 'Missing')], default='complete', max_length=20)),
                ('gap_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('design_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design_controls.designinput')),
                ('design_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design_controls.designoutput')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_links', to='design_controls.designproject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user_need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design_controls.userneed')),
                ('vv_protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design_controls.vvprotocol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='designproject',
            index=models.Index(fields=['project_id'], name='design_cont_project_6c72a6_idx'),
        ),
        migrations.AddIndex(
            model_name='designproject',
            index=models.Index(fields=['status'], name='design_cont_status_3a6b14_idx'),
        ),
        migrations.AddIndex(
            model_name='designproject',
            index=models.Index(fields=['current_phase'], name='design_cont_current_eecabb_idx'),
        ),
        migrations.AddIndex(
            model_name='designoutput',
            index=models.Index(fields=['output_id'], name='design_cont_output__be9b40_idx'),
        ),
        migrations.AddIndex(
            model_name='designoutput',
            index=models.Index(fields=['project'], name='design_cont_project_a8fede_idx'),
        ),
        migrations.AddIndex(
            model_name='designoutput',
            index=models.Index(fields=['status'], name='design_cont_status_8d3cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='designreview',
            index=models.Index(fields=['review_id'], name='design_cont_review__55e026_idx'),
        ),
        migrations.AddIndex(
            model_name='designreview',
            index=models.Index(fields=['project'], name='design_cont_project_17022e_idx'),
        ),
        migrations.AddIndex(
            model_name='designreview',
            index=models.Index(fields=['status'], name='design_cont_status_0f49a1_idx'),
        ),
        migrations.AddIndex(
            model_name='designtransfer',
            index=models.Index(fields=['transfer_id'], name='design_cont_transfe_1228ba_idx'),
        ),
        migrations.AddIndex(
            model_name='designtransfer',
            index=models.Index(fields=['project'], name='design_cont_project_987319_idx'),
        ),
        migrations.AddIndex(
            model_name='designtransfer',
            index=models.Index(fields=['status'], name='design_cont_status_d522f4_idx'),
        ),
        migrations.AddIndex(
            model_name='userneed',
            index=models.Index(fields=['need_id'], name='design_cont_need_id_7d09f3_idx'),
        ),
        migrations.AddIndex(
            model_name='userneed',
            index=models.Index(fields=['project'], name='design_cont_project_65c2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='userneed',
            index=models.Index(fields=['status'], name='design_cont_status_d24123_idx'),
        ),
        migrations.AddIndex(
            model_name='designinput',
            index=models.Index(fields=['input_id'], name='design_cont_input_i_be2210_idx'),
        ),
        migrations.AddIndex(
            model_name='designinput',
            index=models.Index(fields=['project'], name='design_cont_project_fe67b3_idx'),
        ),
        migrations.AddIndex(
            model_name='designinput',
            index=models.Index(fields=['status'], name='design_cont_status_b56289_idx'),
        ),
        migrations.AddIndex(
            model_name='vvprotocol',
            index=models.Index(fields=['protocol_id'], name='design_cont_protoco_577875_idx'),
        ),
        migrations.AddIndex(
            model_name='vvprotocol',
            index=models.Index(fields=['project'], name='design_cont_project_5c0396_idx'),
        ),
        migrations.AddIndex(
            model_name='vvprotocol',
            index=models.Index(fields=['status'], name='design_cont_status_b839f7_idx'),
        ),
        migrations.AddIndex(
            model_name='traceabilitylink',
            index=models.Index(fields=['project'], name='design_cont_project_3f6983_idx'),
        ),
        migrations.AddIndex(
            model_name='traceabilitylink',
            index=models.Index(fields=['link_status'], name='design_cont_link_st_2a9739_idx'),
        ),
    ]
