# Generated by Django 5.2.11 on 2026-02-25 01:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeControlApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_role', models.CharField(choices=[('department_head', 'Department Head'), ('qa_manager', 'QA Manager'), ('regulatory', 'Regulatory Affairs'), ('management', 'Management'), ('technical', 'Technical Expert')], max_length=50)),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='pending', max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Change Control Approval',
                'verbose_name_plural': 'Change Control Approvals',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeControlAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='change_controls/attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Change Control Attachment',
                'verbose_name_plural': 'Change Control Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeControlComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Change Control Comment',
                'verbose_name_plural': 'Change Control Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeControlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('sequence', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Change Control Task',
                'verbose_name_plural': 'Change Control Tasks',
                'ordering': ['sequence', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ChangeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('change_control_id', models.CharField(editable=False, help_text='Auto-generated identifier in format CC-YYYY-NNNN', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('change_type', models.CharField(choices=[('document', 'Document Change'), ('process', 'Process Change'), ('system', 'System Change'), ('equipment', 'Equipment Change'), ('supplier', 'Supplier Change'), ('material', 'Material Change'), ('facility', 'Facility Change'), ('software', 'Software Change'), ('personnel', 'Personnel Change'), ('regulatory', 'Regulatory Change')], max_length=50)),
                ('change_category', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('emergency', 'Emergency')], max_length=50)),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50)),
                ('current_stage', models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('impact_assessment', 'Impact Assessment'), ('approval', 'Approval'), ('implementation', 'Implementation'), ('verification', 'Verification'), ('closed', 'Closed')], default='submitted', max_length=50)),
                ('stage_entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('affected_areas', models.JSONField(blank=True, default=list, help_text='List of affected areas')),
                ('affected_documents', models.JSONField(blank=True, default=list, help_text='List of affected document IDs')),
                ('affected_processes', models.JSONField(blank=True, default=list, help_text='List of affected processes')),
                ('affected_products', models.JSONField(blank=True, default=list, help_text='List of affected products')),
                ('impact_summary', models.TextField(blank=True)),
                ('quality_impact', models.TextField(blank=True)),
                ('regulatory_impact', models.TextField(blank=True)),
                ('safety_impact', models.TextField(blank=True)),
                ('training_impact', models.BooleanField(default=False)),
                ('validation_impact', models.BooleanField(default=False)),
                ('documentation_impact', models.BooleanField(default=False)),
                ('justification', models.TextField(blank=True)),
                ('proposed_implementation_date', models.DateTimeField(blank=True, null=True)),
                ('actual_implementation_date', models.DateTimeField(blank=True, null=True)),
                ('rollback_plan', models.TextField(blank=True)),
                ('verification_method', models.TextField(blank=True)),
                ('verification_results', models.TextField(blank=True)),
                ('verification_completed', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_completion_date', models.DateTimeField(blank=True, null=True)),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('requires_validation', models.BooleanField(default=False)),
                ('requires_regulatory_notification', models.BooleanField(default=False)),
                ('is_emergency', models.BooleanField(default=False)),
                ('affected_departments', models.ManyToManyField(blank=True, related_name='change_controls', to='users.department')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_change_controls', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_change_controls', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_controls_assigned', to='users.department')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_controls_proposed', to=settings.AUTH_USER_MODEL)),
                ('related_capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_controls', to='capa.capa')),
            ],
            options={
                'verbose_name': 'Change Control',
                'verbose_name_plural': 'Change Controls',
                'ordering': ['-submitted_date'],
            },
        ),
    ]
