# Generated by Django 5.2.11 on 2026-02-25 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('change_controls', '0001_initial'),
        ('core', '0001_initial'),
        ('deviations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changecontrol',
            name='related_deviation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_controls', to='deviations.deviation'),
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='sponsor',
            field=models.ForeignKey(blank=True, help_text='Management sponsor for the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_change_controls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_controls_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changecontrolapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_control_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changecontrolapproval',
            name='change_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='change_controls.changecontrol'),
        ),
        migrations.AddField(
            model_name='changecontrolapproval',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changecontrolapproval',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_control_approvals', to='core.electronicsignature'),
        ),
        migrations.AddField(
            model_name='changecontrolapproval',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changecontrolattachment',
            name='change_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='change_controls.changecontrol'),
        ),
        migrations.AddField(
            model_name='changecontrolattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_control_attachments_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changecontrolcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_control_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changecontrolcomment',
            name='change_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='change_controls.changecontrol'),
        ),
        migrations.AddField(
            model_name='changecontrolcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='change_controls.changecontrolcomment'),
        ),
        migrations.AddField(
            model_name='changecontroltask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_change_control_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changecontroltask',
            name='change_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='change_controls.changecontrol'),
        ),
        migrations.AddField(
            model_name='changecontroltask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changecontroltask',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['change_control_id'], name='change_cont_change__55c5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['current_stage'], name='change_cont_current_2c69b6_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['change_type'], name='change_cont_change__0cffcf_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['change_category'], name='change_cont_change__58cfa5_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['risk_level'], name='change_cont_risk_le_4b9b02_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['submitted_date'], name='change_cont_submitt_caa945_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['department'], name='change_cont_departm_45be3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='changecontrolapproval',
            unique_together={('change_control', 'approver')},
        ),
    ]
