# Generated by Django 5.2.11 on 2026-02-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_controls', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changecontrol',
            name='all_child_tasks_complete',
            field=models.BooleanField(default=False, help_text='All child implementation tasks are complete'),
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='effectiveness_check_date',
            field=models.DateField(blank=True, help_text='Scheduled date for effectiveness check', null=True),
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='effectiveness_check_required',
            field=models.BooleanField(default=False, help_text='Whether post-implementation effectiveness check is required'),
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='effectiveness_check_result',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('effective', 'Effective'), ('not_effective', 'Not Effective')], default='pending', help_text='Result of effectiveness check', max_length=20),
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='impact_assessment_checklist',
            field=models.JSONField(blank=True, default=dict, help_text='Checklist: requires_revalidation, risk_file_update, regulatory_submission, training'),
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='regulatory_submission_required',
            field=models.BooleanField(default=False, help_text='Whether regulatory submission is required'),
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='regulatory_submission_status',
            field=models.CharField(blank=True, choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='not_required', help_text='Status of regulatory submission', max_length=20),
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='regulatory_submission_type',
            field=models.CharField(blank=True, help_text='Type of regulatory submission (e.g., 510k, PMA)', max_length=50, null=True),
        ),
    ]
