# Generated by Django 5.2.11 on 2026-02-25 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_id', models.CharField(help_text="Auto-generated unique document identifier (e.g., 'SOP-001')", max_length=50, unique=True)),
                ('title', models.CharField(help_text='Official document title', max_length=500)),
                ('abbreviation', models.CharField(blank=True, help_text='Short abbreviation or acronym for this document', max_length=50)),
                ('business_unit', models.CharField(blank=True, help_text="Business unit or function (e.g., 'Manufacturing', 'QA', 'R&D')", max_length=100)),
                ('site', models.CharField(blank=True, help_text='Physical site or location where document applies', max_length=100)),
                ('major_version', models.PositiveIntegerField(default=1, help_text='Major version number (significant changes)')),
                ('minor_version', models.PositiveIntegerField(default=0, help_text='Minor version number (incremental updates)')),
                ('revision_number', models.PositiveIntegerField(default=0, help_text='Revision number for draft changes')),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes in current version')),
                ('vault_state', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('archived', 'Archived'), ('obsolete', 'Obsolete')], default='draft', help_text='Current lifecycle state of document', max_length=20)),
                ('lifecycle_stage', models.CharField(blank=True, help_text='Current stage in approval/release workflow', max_length=100)),
                ('is_locked', models.BooleanField(default=False, help_text='Whether document is locked from further edits')),
                ('locked_at', models.DateTimeField(blank=True, help_text='Timestamp when document was locked', null=True)),
                ('lock_reason', models.TextField(blank=True, help_text='Reason for document lock')),
                ('effective_date', models.DateField(blank=True, help_text='Date when document becomes effective', null=True)),
                ('next_review_date', models.DateField(blank=True, help_text='Scheduled date for next document review', null=True)),
                ('last_reviewed_date', models.DateField(blank=True, help_text='Date when document was last reviewed', null=True)),
                ('released_date', models.DateTimeField(blank=True, help_text='Date when document was released to production', null=True)),
                ('obsolete_date', models.DateField(blank=True, help_text='Date when document became obsolete', null=True)),
                ('archived_date', models.DateField(blank=True, help_text='Date when document was archived', null=True)),
                ('review_period_months', models.PositiveIntegerField(default=24, help_text='Document review period in months (determines next_review_date)')),
                ('file', models.FileField(blank=True, help_text='Primary document file', null=True, upload_to='documents/%Y/%m/')),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash of uploaded file for integrity verification', max_length=64)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size of uploaded file in bytes', null=True)),
                ('file_type', models.CharField(blank=True, help_text="MIME type of uploaded file (e.g., 'application/pdf')", max_length=50)),
                ('original_filename', models.CharField(blank=True, help_text='Original filename as uploaded', max_length=255)),
                ('external_file_url', models.URLField(blank=True, help_text='URL to external file if not stored locally')),
                ('regulatory_requirement', models.TextField(blank=True, help_text='Specific regulatory requirement(s) this document addresses')),
                ('requires_training', models.BooleanField(default=False, help_text='Whether employees require training on this document')),
                ('training_applicable_roles', models.JSONField(default=list, help_text='List of roles requiring training on this document')),
                ('distribution_restriction', models.CharField(choices=[('none', 'No Restriction'), ('internal', 'Internal Use Only'), ('confidential', 'Confidential'), ('restricted', 'Restricted Distribution')], default='none', help_text='Distribution restriction level', max_length=20)),
                ('confidentiality_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('strictly_confidential', 'Strictly Confidential')], default='internal', help_text='Data confidentiality classification', max_length=25)),
                ('subject_keywords', models.JSONField(default=list, help_text="Keywords for search and classification (e.g., ['sterilization', 'validation'])")),
                ('ai_classification', models.CharField(blank=True, help_text='AI-generated document classification', max_length=100)),
                ('ai_confidence', models.FloatField(blank=True, help_text='Confidence score (0-1) for AI classification', null=True)),
                ('ai_classification_date', models.DateTimeField(blank=True, help_text='Timestamp when AI classification was performed', null=True)),
                ('requires_approval', models.BooleanField(default=True, help_text='Whether document requires formal approval before release')),
                ('is_template', models.BooleanField(default=False, help_text='Whether this document is a template for other documents')),
                ('is_controlled_copy', models.BooleanField(default=True, help_text='Whether this is a controlled master copy')),
                ('has_attachments', models.BooleanField(default=False, help_text='Whether document has related attachments')),
                ('custom_fields', models.JSONField(default=dict, help_text='Flexible key-value pairs for client-specific requirements')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department responsible for this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='users.department')),
                ('locked_by', models.ForeignKey(blank=True, help_text='User who locked this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_documents', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Document owner responsible for maintenance and updates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, help_text='Previous version of this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_number', models.CharField(help_text='Unique identifier for this change order', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Summary of the proposed change', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the change')),
                ('reason_for_change', models.TextField(help_text='Business or technical reason for this change')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented'), ('closed', 'Closed')], default='submitted', help_text='Current status of this change order', max_length=20)),
                ('impact_assessment', models.TextField(blank=True, help_text='Assessment of impacts from this change')),
                ('regulatory_impact', models.BooleanField(default=False, help_text='Whether this change impacts regulatory compliance')),
                ('training_impact', models.BooleanField(default=False, help_text='Whether this change requires employee training')),
                ('affected_processes', models.JSONField(default=list, help_text='List of processes/departments affected by this change')),
                ('implementation_date', models.DateField(blank=True, help_text='Planned implementation date for this change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when change order was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when change order was last updated')),
                ('document', models.ForeignKey(help_text='Document being changed', on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='documents.document')),
                ('proposed_by', models.ForeignKey(help_text='User who submitted this change request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Change Order',
                'verbose_name_plural': 'Document Change Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChangeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval decision', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Approver comments on the change')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp of approval decision', null=True)),
                ('approver', models.ForeignKey(help_text='User approving/rejecting this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_approvals', to=settings.AUTH_USER_MODEL)),
                ('change_order', models.ForeignKey(help_text='Change order being approved', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='documents.documentchangeorder')),
            ],
            options={
                'verbose_name': 'Document Change Approval',
                'verbose_name_plural': 'Document Change Approvals',
                'ordering': ['-approved_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when document was checked out')),
                ('checkout_reason', models.TextField(blank=True, help_text='Reason for checking out the document')),
                ('expected_checkin_date', models.DateTimeField(blank=True, help_text='Expected date when document will be checked back in', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this checkout is currently active')),
                ('checked_out_by', models.ForeignKey(help_text='User who checked out the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_documents', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(help_text='Document being edited', on_delete=django.db.models.deletion.CASCADE, related_name='active_checkout', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Checkout',
                'verbose_name_plural': 'Document Checkouts',
            },
        ),
        migrations.CreateModel(
            name='DocumentInfocardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Name of the document type (e.g., 'Standard Operating Procedure')", max_length=100, unique=True)),
                ('prefix', models.CharField(help_text="3-character unique prefix for auto-generated document IDs (e.g., 'SOP')", max_length=3, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this document type and its usage')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this document type is available for use')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Infocard Type',
                'verbose_name_plural': 'Document Infocard Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='infocard_type',
            field=models.ForeignKey(help_text='Document classification type (SOP, Form, Work Instruction, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentinfocardtype'),
        ),
        migrations.CreateModel(
            name='DocumentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_string', models.CharField(help_text="Version string at time of snapshot (e.g., '2.1')", max_length=20)),
                ('snapshot_type', models.CharField(choices=[('release', 'Release'), ('approval', 'Approval'), ('archive', 'Archive'), ('review', 'Review')], help_text='Type of lifecycle event triggering this snapshot', max_length=20)),
                ('snapshot_data', models.JSONField(help_text='Immutable frozen state of entire document at this point')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when snapshot was created')),
                ('created_by', models.ForeignKey(help_text='User who created this snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_snapshots', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Document being snapshotted', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Snapshot',
                'verbose_name_plural': 'Document Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of this document subtype', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this document subtype')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subtype is available for use')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('infocard_type', models.ForeignKey(help_text='Parent document infocard type', on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='documents.documentinfocardtype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document SubType',
                'verbose_name_plural': 'Document SubTypes',
                'ordering': ['infocard_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='subtype',
            field=models.ForeignKey(blank=True, help_text='Document subtype for further categorization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentsubtype'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('major_version', models.PositiveIntegerField(help_text='Major version number (increments on significant changes)')),
                ('minor_version', models.PositiveIntegerField(default=0, help_text='Minor version number (increments on updates)')),
                ('change_type', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('editorial', 'Editorial')], default='minor', help_text='Type of change in this version', max_length=20)),
                ('is_major_change', models.BooleanField(default=False, help_text='Whether this is a major version change requiring all approvals')),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes in this version')),
                ('snapshot_data', models.JSONField(help_text='Frozen state of document at this version point')),
                ('released_date', models.DateTimeField(blank=True, help_text='Date when this version was released', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Document this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['-major_version', '-minor_version'],
            },
        ),
        migrations.CreateModel(
            name='DocumentApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Order in approval chain (lower number = earlier approval)')),
                ('role_required', models.CharField(blank=True, help_text="Required role/title for this approval step (e.g., 'QA Manager')", max_length=100)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='pending', help_text='Current approval status', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when approval was given', null=True)),
                ('comments', models.TextField(blank=True, help_text='Approver comments on the document')),
                ('approver', models.ForeignKey(help_text='User responsible for approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_to_approve', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Document requiring approval', on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='documents.document')),
                ('signature', models.ForeignKey(blank=True, help_text='Electronic signature for this approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_approvals', to='core.electronicsignature')),
            ],
            options={
                'verbose_name': 'Document Approver',
                'verbose_name_plural': 'Document Approvers',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['document', 'sequence'], name='documents_d_documen_e17e99_idx'), models.Index(fields=['approval_status'], name='documents_d_approva_cb5e83_idx'), models.Index(fields=['approver', 'approval_status'], name='documents_d_approve_9e731b_idx')],
                'unique_together': {('document', 'approver')},
            },
        ),
        migrations.AddIndex(
            model_name='documentchangeorder',
            index=models.Index(fields=['document', 'status'], name='documents_d_documen_28573e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchangeorder',
            index=models.Index(fields=['change_number'], name='documents_d_change__21f86f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchangeorder',
            index=models.Index(fields=['status'], name='documents_d_status_aac643_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchangeorder',
            index=models.Index(fields=['regulatory_impact'], name='documents_d_regulat_cceb1a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchangeapproval',
            index=models.Index(fields=['change_order', 'status'], name='documents_d_change__e76920_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchangeapproval',
            index=models.Index(fields=['approver'], name='documents_d_approve_a63ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcheckout',
            index=models.Index(fields=['is_active', 'checked_out_by'], name='documents_d_is_acti_cbea3f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcheckout',
            index=models.Index(fields=['document', 'is_active'], name='documents_d_documen_a0c948_idx'),
        ),
        migrations.AddIndex(
            model_name='documentinfocardtype',
            index=models.Index(fields=['prefix'], name='documents_d_prefix_17ccdc_idx'),
        ),
        migrations.AddIndex(
            model_name='documentinfocardtype',
            index=models.Index(fields=['is_active'], name='documents_d_is_acti_b36afa_idx'),
        ),
        migrations.AddIndex(
            model_name='documentinfocardtype',
            index=models.Index(fields=['name'], name='documents_d_name_8d43dd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsnapshot',
            index=models.Index(fields=['document', 'snapshot_type'], name='documents_d_documen_47f3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsnapshot',
            index=models.Index(fields=['created_at'], name='documents_d_created_a2231e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsubtype',
            index=models.Index(fields=['infocard_type', 'is_active'], name='documents_d_infocar_719dad_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsubtype',
            index=models.Index(fields=['name'], name='documents_d_name_9211d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentsubtype',
            unique_together={('infocard_type', 'name')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_id'], name='documents_d_documen_612cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['vault_state'], name='documents_d_vault_s_3ca4ef_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['infocard_type', 'vault_state'], name='documents_d_infocar_048073_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['department', 'vault_state'], name='documents_d_departm_2bd437_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner'], name='documents_d_owner_i_fa3cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_by'], name='documents_d_created_54b6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_locked'], name='documents_d_is_lock_aa8d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['next_review_date'], name='documents_d_next_re_1c7c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['released_date'], name='documents_d_release_0443a7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['requires_approval'], name='documents_d_require_d34f38_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['requires_training'], name='documents_d_require_3e0294_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_template'], name='documents_d_is_temp_62407b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['major_version', 'minor_version'], name='documents_d_major_v_e68796_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='documents_d_title_ccf306_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='documents_d_created_71dced_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'major_version'], name='documents_d_documen_a3ba74_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['released_date'], name='documents_d_release_dd3f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['change_type'], name='documents_d_change__389544_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'major_version', 'minor_version')},
        ),
    ]
