# Generated by Django 5.2.11 on 2026-02-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='legacy_document_id',
            field=models.CharField(blank=True, db_index=True, help_text="Legacy document ID from paper-based QMS (e.g., 'QA001-03')", max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.CharField(help_text="Auto-generated unique document identifier (e.g., 'SOP-2026-0001')", max_length=50, unique=True),
        ),
    ]
