# Generated by Django 5.2.11 on 2026-02-26 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_legacy_document_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='TipTap/ProseMirror JSON document structure for in-browser editing'),
        ),
        migrations.AddField(
            model_name='document',
            name='content_html',
            field=models.TextField(blank=True, default='', help_text='Rendered HTML of the document content (auto-generated from content JSON)'),
        ),
        migrations.AddField(
            model_name='document',
            name='content_plain_text',
            field=models.TextField(blank=True, default='', help_text='Plain text extraction for full-text search'),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Brief document description / abstract'),
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField(help_text='Comment text / correction note')),
                ('comment_type', models.CharField(choices=[('comment', 'Comment'), ('correction', 'Correction Required'), ('suggestion', 'Suggestion'), ('question', 'Question')], default='comment', max_length=20)),
                ('selection_from', models.PositiveIntegerField(blank=True, help_text='ProseMirror position: start of highlighted text', null=True)),
                ('selection_to', models.PositiveIntegerField(blank=True, help_text='ProseMirror position: end of highlighted text', null=True)),
                ('quoted_text', models.TextField(blank=True, default='', help_text='The text that was selected when the comment was made')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('wont_fix', "Won't Fix")], default='open', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('document_version', models.CharField(blank=True, default='', help_text="Document version when comment was created (e.g., '3.0')", max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_comments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment (for threaded replies)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='documents.documentcomment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['selection_from', 'created_at'],
                'indexes': [models.Index(fields=['document', 'status'], name='documents_d_documen_df7982_idx'), models.Index(fields=['document', 'author'], name='documents_d_documen_b343f2_idx'), models.Index(fields=['parent'], name='documents_d_parent__22e0a5_idx')],
            },
        ),
    ]
