# Generated by Django 5.2.11 on 2026-02-26 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_content_document_content_html_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('suggestion_type', models.CharField(choices=[('replace', 'Replace Text'), ('insert', 'Insert Text'), ('delete', 'Delete Text'), ('format', 'Format Change')], default='replace', max_length=20)),
                ('selection_from', models.PositiveIntegerField(help_text='ProseMirror position: start of affected text')),
                ('selection_to', models.PositiveIntegerField(help_text='ProseMirror position: end of affected text')),
                ('original_text', models.TextField(blank=True, default='', help_text='Original text being replaced/deleted')),
                ('suggested_text', models.TextField(blank=True, default='', help_text='Suggested replacement text (empty for deletions)')),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for the suggested change')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('document_version', models.CharField(blank=True, default='', help_text='Document version when suggestion was created', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_suggestions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='documents.document')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['selection_from', 'created_at'],
                'indexes': [models.Index(fields=['document', 'status'], name='documents_d_documen_ea921e_idx'), models.Index(fields=['document', 'author'], name='documents_d_documen_7014b5_idx'), models.Index(fields=['status'], name='documents_d_status_94c1db_idx')],
            },
        ),
    ]
