# Generated by Django 5.2.11 on 2026-02-26 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentsuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='requires_dual_approval',
            field=models.BooleanField(default=False, help_text='Requires both Pharma QA and Device QA approval'),
        ),
        migrations.AddField(
            model_name='document',
            name='review_frequency_days',
            field=models.IntegerField(blank=True, help_text='Days between periodic reviews', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='watermark_text',
            field=models.CharField(blank=True, default='Uncontrolled Copy if Printed', help_text='Watermark text for printed copies', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='DocumentAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when document was acknowledged')),
                ('method', models.CharField(choices=[('read', 'Read & Understood'), ('quiz', 'Completed Quiz'), ('signature', 'Electronic Signature')], default='read', help_text='Method of acknowledgment', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Document being acknowledged', on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User acknowledging the document', on_delete=django.db.models.deletion.CASCADE, related_name='doc_acknowledgments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Acknowledgment',
                'verbose_name_plural': 'Document Acknowledgments',
                'ordering': ['-acknowledged_at'],
                'indexes': [models.Index(fields=['document', 'user'], name='documents_d_documen_f2a335_idx'), models.Index(fields=['acknowledged_at'], name='documents_d_acknowl_0caa1f_idx')],
                'unique_together': {('document', 'user')},
            },
        ),
    ]
