# Generated by Django 5.2.11 on 2026-02-26 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_requires_dual_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcheckout',
            name='document',
            field=models.ForeignKey(help_text='Document being edited', on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='documents.document'),
        ),
    ]
