# Generated by Django 5.2.11 on 2026-02-27 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_documentcheckout_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approved_date',
            field=models.DateTimeField(blank=True, help_text='Date when document was formally approved', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for document cancellation'),
        ),
        migrations.AddField(
            model_name='document',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='User who cancelled this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, help_text='Date when document was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='Document that supersedes this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes_documents', to='documents.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='training_completed_date',
            field=models.DateTimeField(blank=True, help_text='Date when all required training was completed', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='training_completion_deadline_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days allowed for training completion after approval'),
        ),
        migrations.AddField(
            model_name='document',
            name='training_completion_required',
            field=models.BooleanField(default=False, help_text='Whether all training must be completed before document becomes effective'),
        ),
        migrations.AddField(
            model_name='document',
            name='workflow_category',
            field=models.CharField(blank=True, choices=[('full_governance', 'Full Governance'), ('standard', 'Standard'), ('simplified', 'Simplified'), ('technical', 'Technical'), ('design_control', 'Design Control'), ('regulatory', 'Regulatory'), ('risk_management', 'Risk Management'), ('legal_contracts', 'Legal/Contracts'), ('training', 'Training')], default='standard', help_text='Workflow category determining approval requirements', max_length=50),
        ),
        migrations.AddField(
            model_name='documentapprover',
            name='is_final_approver',
            field=models.BooleanField(default=False, help_text='Whether this is the final approver in the chain'),
        ),
        migrations.AlterField(
            model_name='document',
            name='vault_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('training_period', 'Training Period'), ('effective', 'Effective'), ('superseded', 'Superseded'), ('obsolete', 'Obsolete'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='draft', help_text='Current lifecycle state of document', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentsnapshot',
            name='snapshot_type',
            field=models.CharField(choices=[('release', 'Release'), ('approval', 'Approval'), ('archive', 'Archive'), ('review', 'Review'), ('training_complete', 'Training Complete'), ('effective', 'Effective'), ('superseded', 'Superseded'), ('cancelled', 'Cancelled')], help_text='Type of lifecycle event triggering this snapshot', max_length=20),
        ),
    ]
