# Generated by Django 5.2.11 on 2026-02-27 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_approved_date_document_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(default=list, help_text='List of roles assigned, e.g. ["author", "reviewer_only"]')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('removed', 'Removed')], default='pending', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(help_text='User who added this collaborator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborators_added', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Document this collaborator is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='documents.document')),
                ('user', models.ForeignKey(help_text='User assigned as collaborator', on_delete=django.db.models.deletion.CASCADE, related_name='document_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('document', 'user')},
            },
        ),
    ]
