# Generated by Django 5.2.11 on 2026-02-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_documentcollaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='columns_count',
            field=models.IntegerField(default=1, help_text='Number of columns in document layout'),
        ),
        migrations.AddField(
            model_name='document',
            name='editor_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores all editor UI state (theme, page color, columns, page borders, headers/footers content, protection settings, etc.)'),
        ),
        migrations.AddField(
            model_name='document',
            name='footer_content',
            field=models.TextField(blank=True, default='', help_text='Footer HTML content'),
        ),
        migrations.AddField(
            model_name='document',
            name='header_content',
            field=models.TextField(blank=True, default='', help_text='Header HTML content'),
        ),
        migrations.AddField(
            model_name='document',
            name='page_color',
            field=models.CharField(blank=True, default='', help_text='Page background color', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='theme_id',
            field=models.CharField(blank=True, default='office', help_text='Theme identifier for document styling', max_length=50),
        ),
    ]
