# Generated by Django 5.2.11 on 2026-02-24 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint_id', models.CharField(max_length=50, unique=True)),
                ('product', models.CharField(max_length=255)),
                ('batch_lot', models.CharField(blank=True, max_length=100)),
                ('customer', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_investigation', 'Under Investigation'), ('capa_initiated', 'CAPA Initiated'), ('investigation_complete', 'Investigation Complete'), ('closed', 'Closed')], default='new', max_length=50)),
                ('reportable', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('under_review', 'Under Review')], default='under_review', max_length=20)),
                ('complaint_date', models.DateField()),
                ('investigation_summary', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('impact_assessment', models.TextField(blank=True)),
                ('ai_triage', models.TextField(blank=True)),
                ('ai_confidence', models.IntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('related_capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='capa.capa')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigation_step', models.CharField(max_length=255)),
                ('findings', models.TextField()),
                ('investigation_date', models.DateField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='complaints.complaint')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('investigator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_investigations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Investigation',
                'verbose_name_plural': 'Complaint Investigations',
                'ordering': ['-investigation_date'],
            },
        ),
    ]
