# Generated by Django 5.2.11 on 2026-02-25 01:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_mgmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPAApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phase', models.CharField(choices=[('investigation', 'Investigation'), ('root_cause', 'Root Cause Analysis'), ('risk_affirmation', 'Risk Affirmation'), ('capa_plan', 'CAPA Plan'), ('implementation', 'Implementation'), ('effectiveness', 'Effectiveness Verification'), ('closure', 'Closure')], max_length=50)),
                ('approval_tier', models.CharField(choices=[('coordinator', 'CAPA Coordinator'), ('manager', 'Department Manager'), ('qa_head', 'QA Head'), ('review_board', 'Review Board'), ('regulatory', 'Regulatory')], max_length=20)),
                ('sequence', models.IntegerField(help_text='Approval sequence number (lower = earlier)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the approver responded', null=True)),
            ],
            options={
                'verbose_name': 'CAPA Approval',
                'verbose_name_plural': 'CAPA Approvals',
                'ordering': ['approval_tier', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='CAPAComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('phase', models.CharField(blank=True, choices=[('investigation', 'Investigation'), ('root_cause', 'Root Cause Analysis'), ('risk_affirmation', 'Risk Affirmation'), ('capa_plan', 'CAPA Plan'), ('implementation', 'Implementation'), ('effectiveness', 'Effectiveness Verification'), ('closure', 'Closure')], help_text='Specific phase this comment relates to', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CAPA Comment',
                'verbose_name_plural': 'CAPA Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CAPADocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('investigation', 'Investigation'), ('root_cause', 'Root Cause Analysis'), ('risk_affirmation', 'Risk Affirmation'), ('capa_plan', 'CAPA Plan'), ('implementation', 'Implementation'), ('effectiveness', 'Effectiveness Verification'), ('closure', 'Closure')], max_length=50)),
                ('document_type', models.CharField(choices=[('investigation_report', 'Investigation Report'), ('root_cause_analysis', 'Root Cause Analysis'), ('risk_assessment', 'Risk Assessment'), ('action_plan', 'Action Plan'), ('effectiveness_report', 'Effectiveness Report'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='capa_documents/%Y/%m/%d/')),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash of file for integrity verification', max_length=256)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CAPA Document',
                'verbose_name_plural': 'CAPA Documents',
                'ordering': ['phase', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capa_id', models.CharField(help_text='Auto-generated format: CAPA-YYYY-NNNN', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('complaint', 'Complaint'), ('audit', 'Audit'), ('deviation', 'Deviation'), ('inspection', 'Inspection'), ('management_review', 'Management Review'), ('customer_feedback', 'Customer Feedback'), ('internal_observation', 'Internal Observation'), ('regulatory', 'Regulatory'), ('supplier', 'Supplier')], max_length=50)),
                ('source_reference', models.TextField(blank=True, help_text='Reference number or description of the source')),
                ('category', models.CharField(blank=True, choices=[('product', 'Product'), ('process', 'Process'), ('system', 'System'), ('documentation', 'Documentation'), ('training', 'Training'), ('equipment', 'Equipment'), ('supplier', 'Supplier'), ('regulatory', 'Regulatory')], max_length=50)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('capa_type', models.CharField(choices=[('corrective', 'Corrective'), ('preventive', 'Preventive'), ('both', 'Both Corrective & Preventive')], default='both', max_length=20)),
                ('current_phase', models.CharField(choices=[('investigation', 'Investigation'), ('root_cause', 'Root Cause Analysis'), ('risk_affirmation', 'Risk Affirmation'), ('capa_plan', 'CAPA Plan'), ('implementation', 'Implementation'), ('effectiveness', 'Effectiveness Verification'), ('closure', 'Closure')], default='investigation', max_length=50)),
                ('phase_entered_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when entering current phase')),
                ('what_happened', models.TextField(blank=True, help_text='What problem occurred?')),
                ('when_happened', models.DateTimeField(blank=True, help_text='When did the problem occur?', null=True)),
                ('where_happened', models.TextField(blank=True, help_text='Where did the problem occur?')),
                ('who_affected', models.TextField(blank=True, help_text='Who was affected by the problem?')),
                ('why_happened', models.TextField(blank=True, help_text='Why did the problem happen?')),
                ('how_discovered', models.TextField(blank=True, help_text='How was the problem discovered?')),
                ('root_cause_analysis_method', models.CharField(blank=True, choices=[('five_why', '5 Why Analysis'), ('fishbone', 'Fishbone Diagram'), ('fmea', 'FMEA'), ('fault_tree', 'Fault Tree Analysis'), ('pareto', 'Pareto Analysis'), ('eight_d', '8D Problem Solving'), ('other', 'Other')], max_length=50)),
                ('root_cause', models.TextField(blank=True, help_text='Identified root cause')),
                ('contributing_factors', models.JSONField(blank=True, default=list, help_text='List of contributing factors')),
                ('root_cause_verified', models.BooleanField(default=False, help_text='Has root cause been verified?')),
                ('root_cause_verified_date', models.DateTimeField(blank=True, null=True)),
                ('risk_severity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Severity: 1 (low) to 5 (high)')),
                ('risk_occurrence', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Occurrence: 1 (low) to 5 (high)')),
                ('risk_detection', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Detection: 1 (low) to 5 (high)')),
                ('risk_acceptability', models.CharField(choices=[('acceptable', 'Acceptable'), ('tolerable', 'Tolerable'), ('unacceptable', 'Unacceptable')], default='tolerable', max_length=20)),
                ('pre_action_rpn', models.IntegerField(blank=True, help_text='Risk Priority Number before action (auto-computed)', null=True)),
                ('post_action_rpn', models.IntegerField(blank=True, help_text='Risk Priority Number after action (auto-computed)', null=True)),
                ('planned_actions', models.JSONField(blank=True, default=list, help_text='Planned actions with descriptions, owners, and dates')),
                ('target_completion_date', models.DateField(blank=True, help_text='Target date for CAPA completion', null=True)),
                ('actual_completion_date', models.DateField(blank=True, help_text='Actual date of CAPA completion', null=True)),
                ('implementation_notes', models.TextField(blank=True, help_text='Notes on implementation progress')),
                ('implementation_evidence', models.TextField(blank=True, help_text='Evidence of implementation (documents, records, etc.)')),
                ('implementation_verified', models.BooleanField(default=False, help_text='Has implementation been verified?')),
                ('effectiveness_criteria', models.TextField(blank=True, help_text='Criteria to verify effectiveness')),
                ('effectiveness_check_date', models.DateTimeField(blank=True, help_text='Date when effectiveness was checked', null=True)),
                ('effectiveness_result', models.CharField(choices=[('effective', 'Effective'), ('partially_effective', 'Partially Effective'), ('not_effective', 'Not Effective'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('effectiveness_evidence', models.TextField(blank=True, help_text='Evidence of effectiveness')),
                ('has_extension', models.BooleanField(default=False, help_text='Has an extension been requested?')),
                ('extension_requested_date', models.DateTimeField(blank=True, null=True)),
                ('extension_reason', models.TextField(blank=True, help_text='Reason for extension request')),
                ('extension_new_due_date', models.DateField(blank=True, help_text='New target completion date after extension', null=True)),
                ('extension_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('closure_comments', models.TextField(blank=True, help_text='Comments on CAPA closure')),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Is this a recurring issue?')),
                ('recurrence_count', models.IntegerField(default=0, help_text='Number of times this issue has recurred')),
                ('requires_management_review', models.BooleanField(default=False, help_text='Does this CAPA require management review?')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('audit_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='audit_mgmt.auditfinding')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_closures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CAPA',
                'verbose_name_plural': 'CAPAs',
                'ordering': ['-created_at'],
            },
        ),
    ]
