# Generated by Django 5.2.11 on 2026-02-24 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capa_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('complaint', 'Complaint'), ('internal_audit', 'Internal Audit'), ('incoming_inspection', 'Incoming Inspection'), ('management_review', 'Management Review'), ('process_monitoring', 'Process Monitoring')], max_length=50)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('investigation', 'Investigation'), ('root_cause_analysis', 'Root Cause Analysis'), ('action_planning', 'Action Planning'), ('effectiveness_verification', 'Effectiveness Verification'), ('closed', 'Closed')], default='investigation', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('root_cause_analysis_method', models.CharField(blank=True, max_length=100)),
                ('corrective_actions', models.TextField(blank=True)),
                ('preventive_actions', models.TextField(blank=True)),
                ('verification_method', models.CharField(blank=True, max_length=100)),
                ('verification_results', models.TextField(blank=True)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('ai_root_cause', models.TextField(blank=True)),
                ('ai_confidence', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_owned', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CAPA',
                'verbose_name_plural': 'CAPAs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CAPAAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('corrective', 'Corrective'), ('preventive', 'Preventive')], max_length=20)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='open', max_length=20)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='capa.capa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_actions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
