# Generated by Django 5.2.11 on 2026-02-25 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0002_initial'),
        ('core', '0001_initial'),
        ('deviations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='deviation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='deviations.deviation'),
        ),
        migrations.AddField(
            model_name='capa',
            name='effectiveness_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_effectiveness_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capa',
            name='extension_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_extensions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capa',
            name='implementation_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_implementation_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capa',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_responsible_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capa',
            name='root_cause_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_root_cause_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capaapproval',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capaapproval',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='capa.capa'),
        ),
        migrations.AddField(
            model_name='capaapproval',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capaapproval',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_approvals', to='core.electronicsignature'),
        ),
        migrations.AddField(
            model_name='capaapproval',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacomment',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='capa.capa'),
        ),
        migrations.AddField(
            model_name='capacomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent comment for threading', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='capa.capacomment'),
        ),
        migrations.AddField(
            model_name='capadocument',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='capa.capa'),
        ),
        migrations.AddField(
            model_name='capadocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_documents_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='capa',
            index=models.Index(fields=['capa_id'], name='capa_capa_capa_id_e52985_idx'),
        ),
        migrations.AddIndex(
            model_name='capa',
            index=models.Index(fields=['current_phase'], name='capa_capa_current_a7e115_idx'),
        ),
        migrations.AddIndex(
            model_name='capa',
            index=models.Index(fields=['priority'], name='capa_capa_priorit_428917_idx'),
        ),
        migrations.AddIndex(
            model_name='capa',
            index=models.Index(fields=['source'], name='capa_capa_source_bb8285_idx'),
        ),
        migrations.AddIndex(
            model_name='capa',
            index=models.Index(fields=['department'], name='capa_capa_departm_5ff2ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='capaapproval',
            unique_together={('capa', 'phase', 'approver')},
        ),
    ]
