# Generated by Django 5.2.11 on 2026-02-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_mgmt', '0003_auditfinding_auto_generated_capa_and_more'),
        ('capa', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Auto-generated from audit finding or complaint'),
        ),
        migrations.AddField(
            model_name='capa',
            name='effectiveness_eligible_date',
            field=models.DateField(blank=True, help_text='Date when CAPA is eligible for effectiveness check', null=True),
        ),
        migrations.AddField(
            model_name='capa',
            name='effectiveness_wait_days',
            field=models.IntegerField(blank=True, default=60, help_text='Days to wait before effectiveness check', null=True),
        ),
        migrations.AddField(
            model_name='capa',
            name='investigation_track',
            field=models.CharField(blank=True, choices=[('device', 'Device'), ('pharma', 'Pharma'), ('both', 'Both'), ('na', 'N/A')], default='na', help_text='Investigation track for multi-disciplinary products', max_length=20),
        ),
        migrations.AddField(
            model_name='capa',
            name='parallel_investigation',
            field=models.BooleanField(default=False, help_text='Dual-track investigation for combination products'),
        ),
        migrations.AddField(
            model_name='capa',
            name='similar_capas',
            field=models.ManyToManyField(blank=True, help_text='Related CAPAs with similar root causes', to='capa.capa'),
        ),
        migrations.AddField(
            model_name='capa',
            name='source_audit_finding',
            field=models.ForeignKey(blank=True, help_text='Audit finding that auto-generated this CAPA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_capas', to='audit_mgmt.auditfinding'),
        ),
    ]
