# Generated by Django 5.2.11 on 2026-02-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='feedback',
            field=models.CharField(blank=True, choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('pending', 'Pending')], default='pending', help_text='User feedback on insight usefulness', max_length=20),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='feedback_notes',
            field=models.TextField(blank=True, help_text='User notes on insight feedback', null=True),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='insight_category',
            field=models.CharField(blank=True, choices=[('classification', 'Document Classification'), ('triage', 'Complaint Triage'), ('root_cause', 'Root Cause Prediction'), ('training_gap', 'Training Gap'), ('anomaly', 'Trend Anomaly'), ('similarity', 'Similar Record'), ('general', 'General')], default='general', help_text='Category of AI insight', max_length=30),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='prediction_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional prediction data and parameters'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='source_module',
            field=models.CharField(blank=True, help_text='Module where insight originated (e.g., complaints, deviations)', max_length=30, null=True),
        ),
    ]
