# Generated by Django 5.2.11 on 2026-02-26 01:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingassessment',
            name='assessment_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Exam'), ('survey', 'Survey'), ('practical', 'Practical')], default='quiz', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='auto_assign_on_role_change',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TrainingCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('renewal_period_months', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='training.trainingcourse')),
            ],
            options={
                'verbose_name': 'Training Competency',
                'verbose_name_plural': 'Training Competencies',
                'ordering': ['name'],
            },
        ),
    ]
