# Generated by Django 5.2.11 on 2026-02-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_requires_dual_approval_and_more'),
        ('training', '0002_trainingassessment_assessment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingassignment',
            name='auto_triggered',
            field=models.BooleanField(default=False, help_text='Auto-triggered by SOP update'),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='operational_lockout',
            field=models.BooleanField(default=False, help_text='Block user from operations until training complete'),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='triggering_document',
            field=models.ForeignKey(blank=True, help_text='Document that triggered this training assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_trainings', to='documents.document'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='classroom_attendance_required',
            field=models.BooleanField(default=False, help_text='Whether classroom attendance is required'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='scorm_package',
            field=models.FileField(blank=True, help_text='SCORM package file for e-learning', null=True, upload_to='scorm_packages/'),
        ),
    ]
